import json
import os

# The exact instruction prompt for your LLM
INSTRUCTION = "Explain the answer to the following question as if I were a 5-year-old. Base your explanation strictly on the provided context. Provide ONLY your final explanation. Do not generate any extra documents, follow-up questions, or separators."

def load_data(filepath):
    print(f"Loading {filepath}...")
    with open(filepath, 'r') as file:
        return json.load(file)

def generate_experiment_3b(dataset):
    """
    Experiment 3B: Impact of Random Noise Documents (Answer-Grounded)
    Layout: [ Instruction, N x S (Noise), A (Answers), Question ]
    """
    # The different context lengths (number of noise documents)
    noise_counts = [0, 4, 9, 14, 19, 24, 29]
    
    # Create the output directory
    output_dir = "prompts/exp3b"
    os.makedirs(output_dir, exist_ok=True)

    for count in noise_counts:
        case_prompts = []
        
        for entry in dataset:
            # Safely handle 'question' or 'query' keys depending on your exact org.json schema
            query_id = entry.get('query_id', entry.get('id', 'unknown'))
            question = entry.get('question', entry.get('query', ''))
            
            # 1. Safely Extract and Flatten the Answers
            # This handles the specific list-of-lists format we discovered in your JSON
            answers_data = entry.get('answers', entry.get('answer', []))
            flat_answers = []
            
            if isinstance(answers_data, list):
                for ans in answers_data:
                    # If it's a nested list like [["Answer part 1."]]
                    if isinstance(ans, list) and len(ans) > 0:
                        flat_answers.append(str(ans[0]))
                    # If it's just a normal list of strings
                    elif isinstance(ans, str):
                        flat_answers.append(ans)
            elif isinstance(answers_data, str):
                # Fallback if it's just a single string
                flat_answers.append(answers_data)
                
            answer_text = " ".join(flat_answers)
            
            # 2. Extract the Noise text 
            # ('noise' is already a list of plain strings generated by your previous script)
            noise_docs = entry.get('noise', [])
            
            if len(noise_docs) < count:
                print(f"Warning: Entry {query_id} only has {len(noise_docs)} noise docs, but {count} requested.")
                
            # Slice the array to the required number of noise documents
            S_docs = noise_docs[:count]
            
            # 3. Construct layout: S noise documents followed by the Answer block at the end
            context_blocks = S_docs + [answer_text]
            context_str = "\n\n---\n\n".join(context_blocks)
            
            # 4. Build the final prompt string
            prompt_text = f"{INSTRUCTION}{context_str}\n\nQuestion: {question}\nAnswer:"
            
            case_prompts.append({
                "experiment": "3B",
                "query_id": query_id,
                "noise_count": count,
                "prompt": prompt_text
            })
            
        # Save this specific case to its own isolated JSON file
        filename = f"{output_dir}/{count}_noise_docs.json"
        with open(filename, 'w') as file:
            json.dump(case_prompts, file, indent=4)
            
        print(f"Saved {len(case_prompts)} prompts to {filename}")

if __name__ == "__main__":
    # Point this to the Category B file that was generated by your noise injection script!
    input_file = 'data/processed/eli5_org_with_noise.json' 
    
    if not os.path.exists(input_file):
        print(f"Error: Could not find {input_file}. Make sure you ran the noise injection script first.")
    else:
        dataset = load_data(input_file)
        print("Generating Experiment 3B prompts (using Random Noise)...")
        generate_experiment_3b(dataset)
        print("\nAll cases generated successfully in the 'prompts/exp3b_noise/' directory.")