import json
import os

# The exact instruction prompt for your LLM
INSTRUCTION = "Explain the answer to the following question as if I were a 5-year-old. Base your explanation strictly on the provided context. Provide ONLY your final explanation. Do not generate any extra documents, follow-up questions, or separators."

def load_data(filepath):
    print(f"Loading {filepath}...")
    with open(filepath, 'r') as file:
        return json.load(file)

def generate_experiment_3a(dataset):
    """
    Experiment 3A: Impact of Random Noise Documents
    Layout: [ Instruction, N x S (Noise), G (Gold), Question ]
    """
    # The different context lengths (number of noise documents)
    noise_counts = [0, 4, 9, 14, 19, 24, 29]
    
    # Create the output directory
    output_dir = "prompts/exp3a"
    os.makedirs(output_dir, exist_ok=True)

    for count in noise_counts:
        case_prompts = []
        
        for entry in dataset:
            query_id = entry.get('query_id', 'unknown')
            question = entry.get('question', '')
            
            # 1. Extract the Gold text safely from the dictionary array
            gold_data = entry.get('gold', [])
            gold_text = " ".join([d.get("text", "") for d in gold_data if isinstance(d, dict) and "text" in d])
            
            # 2. Extract the Noise text 
            # (Because of your previous script, 'noise' is already a list of strings, not dictionaries)
            noise_docs = entry.get('noise', [])
            
            if len(noise_docs) < count:
                print(f"Warning: Entry {query_id} only has {len(noise_docs)} noise docs, but {count} requested.")
                
            # Slice the array to the required number of noise documents
            S_docs = noise_docs[:count]
            
            # 3. Construct layout: S noise documents followed by the Gold document at the end
            context_blocks = S_docs + [gold_text]
            context_str = "\n\n---\n\n".join(context_blocks)
            
            # 4. Build the final prompt string
            prompt_text = f"{INSTRUCTION}{context_str}\n\nQuestion: {question}\nAnswer:"
            
            case_prompts.append({
                "experiment": "3A",
                "query_id": query_id,
                "noise_count": count,
                "prompt": prompt_text
            })
            
        # Save this specific case to its own isolated JSON file
        filename = f"{output_dir}/{count}_noise_docs.json"
        with open(filename, 'w') as file:
            json.dump(case_prompts, file, indent=4)
            
        print(f"Saved {len(case_prompts)} prompts to {filename}")

if __name__ == "__main__":
    # Point this to the file that was generated by your noise injection script!
    input_file = 'data/processed/eli5_good_with_noise.json' 
    
    if not os.path.exists(input_file):
        print(f"Error: Could not find {input_file}. Make sure you ran the noise injection script first.")
    else:
        dataset = load_data(input_file)
        print("Generating Experiment 3A prompts (using Random Noise)...")
        generate_experiment_3a(dataset)
        print("\nAll cases generated successfully in the 'prompts/exp3a_noise/' directory.")